openapi: 3.0.3
info:
  title: Liquibase Project - OpenAPI 3.0
  description: |-
    API for managing Users, Products, and Orders
  contact:
    email: <a href="mailto:stefan.golubov@qinshift.com">stefan.golubov@qinshift.com</a>
  version: 1.0.0
servers:
  - url: ${serverUrl}
tags:
  - name: users
    description: List of users
  - name: products
    description: List of products
paths:
  /users:
    $ref: './paths/users.yml#/users'
  /users/findByUsername:
    $ref: './paths/users.yml#/findByUsername'
  /users/findAll:
    $ref: './paths/users.yml#/findAll'
  /users/{id}:
    $ref: './paths/users.yml#/userById'
  /products:
    $ref: './paths/products.yml#/products'
  /products/findByName:
    $ref: './paths/products.yml#/findByName'
  /products/findAll:
    $ref: './paths/products.yml#/findAll'
  /products/{id}:
    $ref: './paths/products.yml#/productById'
components:
  schemas:
    Users:
      $ref: './schemas/users.yml#/Users'
    NewUser:
      $ref: './schemas/users.yml#/NewUser'
    Products:
      $ref: './schemas/products.yml#/Products'
    NewProduct:
      $ref: './schemas/products.yml#/NewProduct'
    ApiResponse:
      $ref: './schemas/apiresponse.yml#/ApiResponse'
  requestBodies:
    Users:
      description: User object that needs to be added
      content:
        application/json:
          schema:
            $ref: './schemas/users.yml#/Users'
        application/xml:
          schema:
            $ref: './schemas/users.yml#/Users'
    UserArray:
      description: List of user object
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: './schemas/users.yml#/Users'
    Products:
      description: Product object that needs to be added
      content:
        application/json:
          schema:
            $ref: './schemas/products.yml#/Products'
        application/xml:
          schema:
            $ref: './schemas/products.yml#/Products'
    ProductArray:
      description: List of product object
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: './schemas/products.yml#/Products'
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header