openapi: 3.0.3
info:
  title: Liquibase Project - OpenAPI 3.0
  description: |-
    API for managing Users, Products, and Orders
  contact:
    email: <a href="mailto:stefan.golubov@qinshift.com">stefan.golubov@qinshift.com</a>
  version: 1.0.0
tags:
  - name: users
    description: List of users
  - name: products
    description: List of products
  - name: orders
    description: List of orders
paths:
  /${users.path}:
    $ref: './paths/users.yml#/users'
  /${users.findByUsername.path}:
    $ref: './paths/users.yml#/findByUsername'
  /${users.findAll.path}:
    $ref: './paths/users.yml#/findAll'
  /${users.id.path}:
    $ref: './paths/users.yml#/userById'
  /${products.path}:
    $ref: './paths/products.yml#/products'
  /${products.findByName.path}:
    $ref: './paths/products.yml#/findByName'
  /${products.findAll.path}:
    $ref: './paths/products.yml#/findAll'
  /${products.id.path}:
    $ref: './paths/products.yml#/productById'
  /${orders.path}:
    $ref: './paths/orders.yml#/orders'
  /${orders.findByIDs.path}:
    $ref: './paths/orders.yml#/findByIDs'
  /${orders.findAll.path}:
    $ref: './paths/orders.yml#/findAll'
  /${orders.id.path}:
    $ref: './paths/orders.yml#/orderById'
components:
  schemas:
    Users:
      $ref: './schemas/users.yml#/Users'
    NewUser:
      $ref: './schemas/users.yml#/NewUser'
    Products:
      $ref: './schemas/products.yml#/Products'
    NewProduct:
      $ref: './schemas/products.yml#/NewProduct'
    Orders:
      $ref: './schemas/orders.yml#/Orders'
    ApiResponseSchema:
      $ref: './schemas/apiresponseschema.yml#/ApiResponseSchema'
  requestBodies:
    Users:
      description: User object that needs to be added
      content:
        application/json:
          schema:
            $ref: './schemas/users.yml#/Users'
        application/xml:
          schema:
            $ref: './schemas/users.yml#/Users'
    UserArray:
      description: List of user object
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: './schemas/users.yml#/Users'
    Products:
      description: Product object that needs to be added
      content:
        application/json:
          schema:
            $ref: './schemas/products.yml#/Products'
        application/xml:
          schema:
            $ref: './schemas/products.yml#/Products'
    ProductArray:
      description: List of product object
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: './schemas/products.yml#/Products'
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic