server:
  port: 8888
spring:
  application:
    name: liquibase-project
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: my_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-liquibase-project.html
    operationsSorter: method
    tagsSorter: alpha

user:
  password: user
admin:
  password: admin