products:
  put:
    tags:
      - products
    summary: Update an existing product
    description: Update an existing product by Id
    operationId: updateProduct
    requestBody:
      description: Update an existing product
      content:
        application/json:
          schema:
            $ref: '../schemas/products.yml#/Products'
        application/xml:
          schema:
            $ref: '../schemas/products.yml#/Products'
        application/x-www-form-urlencoded:
          schema:
            $ref: '../schemas/products.yml#/Products'
      required: true
    responses:
      '200':
        description: Product has been successfully updated
        content:
          application/json:
            schema:
              $ref: '../schemas/apiresponseschema.yml#/ApiResponseSchema'
          application/xml:
            schema:
              $ref: '../schemas/products.yml#/Products'
      '400':
        description: Invalid ID supplied
      '404':
        description: Product not found
      '422':
        description: Validation exception
    security:
      - petstore_auth:
          - write:products
          - read:products
  post:
    tags:
      - products
    summary: Add a new product
    description: Add a new product
    operationId: addProduct
    requestBody:
      description: Create a new product
      content:
        application/json:
          schema:
            $ref: '../schemas/products.yml#/NewProduct'
        application/xml:
          schema:
            $ref: '../schemas/products.yml#/NewProduct'
        application/x-www-form-urlencoded:
          schema:
            $ref: '../schemas/products.yml#/NewProduct'
      required: true
    responses:
      '200':
        description: Product has been successfully added
        content:
          application/json:
            schema:
              $ref: '../schemas/products.yml#/Products'
          application/xml:
            schema:
              $ref: '../schemas/products.yml#/Products'
      '400':
        description: Invalid input
      '422':
        description: Validation exception
    security:
      - petstore_auth:
          - write:products
          - read:products
findByName:
  get:
    tags:
      - products
    summary: Find products by product name
    description: Multiple products can be provided with comma separated strings
    operationId: findProductsByName
    parameters:
      - name: names
        in: query
        required: false
        schema:
          type: string
    responses:
      '200':
        description: Products have been successfully found by product name
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '../schemas/products.yml#/Products'
          application/xml:
            schema:
              type: array
              items:
                $ref: '../schemas/products.yml#/Products'
      '400':
        description: Invalid product name
    security:
      - petstore_auth:
          - write:products
          - read:products
findAll:
  get:
    tags:
      - products
    summary: List all products
    operationId: findAllProducts
    responses:
      '200':
        description: Products have been successfully listed
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '../schemas/products.yml#/Products'
          application/xml:
            schema:
              type: array
              items:
                $ref: '../schemas/products.yml#/Products'
      '404':
        description: The resource path is incorrect
      '500':
        description: Internal Server Error
    security:
      - petstore_auth:
          - write:products
          - read:products
productById:
  get:
    tags:
      - products
    summary: Find product by ID
    description: Returns a single product
    operationId: getProductById
    parameters:
      - name: id
        in: path
        description: Product ID to return
        required: true
        schema:
          type: string
          format: uuid
    responses:
      '200':
        description: Product found by ID
        content:
          application/json:
            schema:
              $ref: '../schemas/products.yml#/Products'
          application/xml:
            schema:
              $ref: '../schemas/products.yml#/Products'
      '400':
        description: Invalid product ID
      '404':
        description: Product not found
    security:
      - api_key: [ ]
      - petstore_auth:
          - write:products
          - read:products
  post:
    tags:
      - products
    summary: Updates a product with form data
    description: ''
    operationId: updateProductWithForm
    parameters:
      - name: id
        in: path
        description: ID of product that needs to be updated
        required: true
        schema:
          type: string
          format: uuid
      - name: name
        in: query
        description: Name for the product that needs to be updated
        schema:
          type: string
      - name: description
        in: query
        description: Description for the product that needs to be updated
        schema:
          type: string
      - name: price
        in: query
        description: Price for the product that needs to be updated
        schema:
          type: number
          format: double
      - name: quantity
        in: query
        description: Quantity of the product that needs to be updated
        schema:
          type: integer
          format: int32
    responses:
      '200':
        description: User found by ID
        content:
          application/json:
            schema:
              $ref: '../schemas/apiresponseschema.yml#/ApiResponseSchema'
          application/xml:
            schema:
              $ref: '../schemas/apiresponseschema.yml#/ApiResponseSchema'
      '400':
        description: Invalid input
    security:
      - petstore_auth:
          - write:products
          - read:products
  delete:
    tags:
      - products
    summary: Deletes a product
    description: delete a product
    operationId: deleteProduct
    parameters:
      - name: api_key
        in: header
        description: ''
        required: false
        schema:
          type: string
      - name: id
        in: path
        description: Product ID for the product that needs to be deleted
        required: true
        schema:
          type: string
          format: uuid
    responses:
      '200':
        description: Product found by ID
        content:
          application/json:
            schema:
              $ref: '../schemas/apiresponseschema.yml#/ApiResponseSchema'
          application/xml:
            schema:
              $ref: '../schemas/apiresponseschema.yml#/ApiResponseSchema'
      '400':
        description: Invalid product ID value
    security:
      - petstore_auth:
          - write:products
          - read:products