apiVersion: apps/v1
kind: Deployment
metadata:
  name: liquibase-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: liquibase-project
  template:
    metadata:
      labels:
        app: liquibase-project
    spec:
      containers:
        - name: liquibase-project
          image: stefangolubov/liquibase-project:latest
          ports:
            - containerPort: 8888
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /actuator/prometheus
              port: 8888
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/prometheus
              port: 8888
            initialDelaySeconds: 60
            periodSeconds: 10
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db:5432/postgres
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: my_password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: my_password