--liquibase formatted sql

--changeset Stefan:createTriggersAndFunction runAlways:true splitStatements:false
--comment: Creating TRG_UPDATE_USERS, TRG_UPDATE_PRODUCTS and FN_UPDATE_TIMESTAMP
--preConditions onFail:MARK_RAN

--sql
CREATE OR REPLACE FUNCTION FN_UPDATE_TIMESTAMP()
RETURNS TRIGGER AS $$
BEGIN
NEW.updated_at = NOW();
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS TRG_UPDATE_USERS on USERS;

CREATE TRIGGER TRG_UPDATE_USERS
BEFORE UPDATE ON USERS
FOR EACH ROW
EXECUTE FUNCTION FN_UPDATE_TIMESTAMP();

DROP TRIGGER IF EXISTS TRG_UPDATE_PRODUCTS on PRODUCTS;

CREATE TRIGGER TRG_UPDATE_PRODUCTS
BEFORE UPDATE ON PRODUCTS
FOR EACH ROW
EXECUTE FUNCTION FN_UPDATE_TIMESTAMP();